version: '3'

services:
  app:
    build:
      context: ./node
    image: nandopx/node:prod
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    tty: true
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - desafio-network
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    image: nandopx/nginx:prod
    container_name: nginx
    networks:
      - desafio-network
    ports:
      - "8080:80"
    depends_on:
      - db
      - app

  db:
    build:
      context: ./mysql
    image: nandopx/mysql:prod
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/db_volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - desafio-network

networks:
    desafio-network:
      driver: bridge